# Generated by Django 5.0 on 2025-04-09 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('seances_travail', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Moniteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cavalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cheval_possede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.cheval')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('cavalier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.cavalier')),
                ('cheval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.cheval')),
                ('entraineur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.moniteur')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('cavalier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.cavalier')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.cours')),
            ],
        ),
    ]
