# Generated by Django 4.2.20 on 2025-04-11 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_alter_cours_options_rename_titre_cours_niveau_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cours", name="cavalier",),
        migrations.RemoveField(model_name="cours", name="cheval",),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cavalier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="club.cavalier"
                    ),
                ),
                (
                    "cheval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="club.cheval"
                    ),
                ),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="club.cours",
                    ),
                ),
            ],
        ),
    ]
