# Generated by Django 4.2.20 on 2025-04-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_remove_cours_cavalier_remove_cours_cheval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheval",
            name="test_champ",
            field=models.BooleanField(default=False),
        ),
    ]
