# Generated by Django 4.2.20 on 2025-04-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0004_cheval_test_champ"),
    ]

    operations = [
        migrations.RemoveField(model_name="cheval", name="test_champ",),
    ]
